### ISSUE TITLE
Crash when viewing weekly summary

### ISSUE THREAD

**Issue by pierg75** [NerdyPepper/dijo#5]
I was trying to add some habit without a specific goal, increased the count of the newly added habit of 1 or 2 and then checked the weekly view. It crashes here.
This is the call trace:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/dijo`
thread 'main' panicked at 'attempt to divide by zero', src/views.rs:84:36
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: <T as dijo::views::ShadowView>::draw::{{closure}}
             at src/views.rs:84
  15: <T as dijo::views::ShadowView>::draw
             at src/views.rs:130
  16: <dijo::habit::count::Count as dijo::habit::traits::HabitWrapper>::draw
  17: dijo::app::impl_view::<impl cursive_core::view::view_trait::View for dijo::app::App>::draw
             at src/app/impl_view.rs:28
  18: cursive_core::view::view_wrapper::ViewWrapper::wrap_draw::{{closure}}
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:51
  19: <cursive_core::views::named_view::NamedView<T> as cursive_core::view::view_wrapper::ViewWrapper>::with_view::{{closure}}
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/named_view.rs:65
  20: core::option::Option<T>::map
             at /home/luser/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/option.rs:456
  21: <cursive_core::views::named_view::NamedView<T> as cursive_core::view::view_wrapper::ViewWrapper>::with_view
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/named_view.rs:65
  22: cursive_core::view::view_wrapper::ViewWrapper::wrap_draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:51
  23: cursive_core::view::view_wrapper::<impl cursive_core::view::view_trait::View for T>::draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:107
  24: <cursive_core::views::linear_layout::LinearLayout as cursive_core::view::view_trait::View>::draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/linear_layout.rs:461
  25: cursive_core::view::view_wrapper::ViewWrapper::wrap_draw::{{closure}}
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:51
  26: <cursive_core::views::named_view::NamedView<T> as cursive_core::view::view_wrapper::ViewWrapper>::with_view::{{closure}}
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/named_view.rs:65
  27: core::option::Option<T>::map
             at /home/luser/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/option.rs:456
  28: <cursive_core::views::named_view::NamedView<T> as cursive_core::view::view_wrapper::ViewWrapper>::with_view
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/named_view.rs:65
  29: cursive_core::view::view_wrapper::ViewWrapper::wrap_draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:51
  30: cursive_core::view::view_wrapper::<impl cursive_core::view::view_trait::View for T>::draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:107
  31: cursive_core::view::view_wrapper::ViewWrapper::wrap_draw::{{closure}}
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:51
  32: <cursive_core::views::boxed_view::BoxedView as cursive_core::view::view_wrapper::ViewWrapper>::with_view
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/boxed_view.rs:52
  33: cursive_core::view::view_wrapper::ViewWrapper::wrap_draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:51
  34: cursive_core::view::view_wrapper::<impl cursive_core::view::view_trait::View for T>::draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:107
  35: cursive_core::view::view_wrapper::ViewWrapper::wrap_draw::{{closure}}
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:51
  36: <cursive_core::views::circular_focus::CircularFocus<T> as cursive_core::view::view_wrapper::ViewWrapper>::with_view
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:176
  37: cursive_core::view::view_wrapper::ViewWrapper::wrap_draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:51
  38: cursive_core::view::view_wrapper::<impl cursive_core::view::view_trait::View for T>::draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:107
  39: <cursive_core::views::layer::Layer<T> as cursive_core::view::view_wrapper::ViewWrapper>::wrap_draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/layer.rs:51
  40: cursive_core::view::view_wrapper::<impl cursive_core::view::view_trait::View for T>::draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:107
  41: <cursive_core::views::shadow_view::ShadowView<T> as cursive_core::view::view_wrapper::ViewWrapper>::wrap_draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/shadow_view.rs:106
  42: cursive_core::view::view_wrapper::<impl cursive_core::view::view_trait::View for T>::draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:107
  43: <cursive_core::views::stack_view::ChildWrapper<T> as cursive_core::view::view_trait::View>::draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/stack_view.rs:136
  44: cursive_core::views::stack_view::StackView::draw_fg::{{closure}}
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/stack_view.rs:550
  45: cursive_core::printer::Printer::with_color
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/printer.rs:310
  46: cursive_core::views::stack_view::StackView::draw_fg
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/stack_view.rs:545
  47: <cursive_core::views::stack_view::StackView as cursive_core::view::view_trait::View>::draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/stack_view.rs:613
  48: cursive_core::view::view_wrapper::ViewWrapper::wrap_draw::{{closure}}
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:51
  49: core::option::Option<T>::map
             at /home/luser/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/option.rs:456
  50: <cursive_core::views::screens_view::ScreensView<V> as cursive_core::view::view_wrapper::ViewWrapper>::with_view
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/views/screens_view.rs:110
  51: cursive_core::view::view_wrapper::ViewWrapper::wrap_draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:51
  52: cursive_core::view::view_wrapper::<impl cursive_core::view::view_trait::View for T>::draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:107
  53: cursive_core::view::view_wrapper::ViewWrapper::wrap_draw::{{closure}}
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:51
  54: <cursive_core::views::on_event_view::OnEventView<T> as cursive_core::view::view_wrapper::ViewWrapper>::with_view
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:176
  55: cursive_core::view::view_wrapper::ViewWrapper::wrap_draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:51
  56: cursive_core::view::view_wrapper::<impl cursive_core::view::view_trait::View for T>::draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/view/view_wrapper.rs:107
  57: cursive_core::cursive::Cursive::draw
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/cursive.rs:833
  58: cursive_core::cursive::Cursive::refresh
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/cursive.rs:987
  59: cursive_core::cursive::Cursive::post_events
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/cursive.rs:967
  60: cursive_core::cursive::Cursive::step
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/cursive.rs:892
  61: cursive_core::cursive::Cursive::run
             at /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/cursive_core-0.1.1/src/cursive.rs:877
  62: dijo::main
             at src/main.rs:63
  63: std::rt::lang_start::{{closure}}
             at /home/luser/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  64: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  65: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  66: std::panicking::try
             at src/libstd/panicking.rs:274
  67: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  68: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  69: std::rt::lang_start
             at /home/luser/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  70: main
  71: __libc_start_main
  72: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

A quick troubleshooting shows that `weekly_goal` at src/views.rs:84 is indeed zero.

**Comment by NerdyPepper** [comment]
Should be fixed on master, this fix will be included in release v0.1.3.
